name: example-environment
channels:
  - conda-forge
dependencies:
  - python
  - numpy
  - scipy
  - h5py
  - geopandas
  - descartes
  - natsort
  - sklearn
  - pip
  - ipywidgets>=0.6.0
  - pip:
    - nbgitpuller
    - sphinx-gallery
    - pandas
    - matplotlib
