name: example-environment
channels:
  - conda-forge
dependencies:
  - python
  - R
  - numpy
  - scipy
  - pip
  - ipywidgets>=0.6.0
  - pip:
    - nbgitpuller
    - sphinx-gallery
    - pandas
    - matplotlib
